title: Olivier Mullier
email: oliviermullier@polytechnique.edu
#url: "http://oliviermullier.github.io"
description: Postdoctoral fellow at ENSTA Paristech, France
github_username:  oliviermullier
linkedin_username: olivier-mullier-93854230
#google_analytics: [Your Google Analytics tracking ID]
#permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown

theme: minima
